version: "3"
services:
  angular:
    image: social-media-angular:0.0.0
    build:
      context: UI
      dockerfile: Dockerfile
    environment:
      - PORT=80
    ports:
      - "80:80"

  spring:
    image: social-media-spring:0.0.1-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    ports:
      - "8080:8080"